

server:
  port: 9001


#默认权限登录用户
spring:
  security:
    user:
      name: admin
      password: 111111
#数据库连接信息
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/transaction_management?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123

  application:
    name: Transaction Management



#Redis连接信息
redis:
  host: localhost
  port: 6379
  jedis:
    pool:
      max-wait: 30000   #最大阻塞时间  -1表示无限制
      max-active: -1    #连接池中最大连接数  -1表示无限制
      max-idle: 20    #连接池中最大空闲数
      min-idle: 0     #连接池中最小空闲数
  timeout: 3000     #连接超时


#开启驼峰命名
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
